### ISSUE TITLE
Map of mobile data squashed with smaller window size

### ISSUE THREAD

**Issue by rt17603** [openghg/dashboard#90]
The issue with the map and text has been fixed for the top two panels but for the mobile data, the mobile map (on the left) is now not only displaying as a thin and tall window. I've included a screen shot of this:

![Dashboard_mobile_map_2021-11-01](https://user-images.githubusercontent.com/37222223/139708933-29ddabe4-9046-4436-b2fc-cd6afbbf4138.png)

For reference, my laptop is a Latitude 7390 (slimline university laptop) with screen size:
 - Height:165.08 mm
 - Width: 293.47 mm
 - Diagonal: 13.3 inch
 - Resolution: 1920 x 1080

**Comment by gareth-j** [comment]
This was fixed with #94.
